export const DISEASES = [
  "Fibromyalgia",
  "Systemic Lupus Erythematosus",
  "Rheumatoid Arthritis",
  "Sjögren’s Syndrome",
  "Multiple Sclerosis",
  "Ankylosing Spondylitis",
  "Polymyalgia Rheumatica",
  "Mixed Connective Tissue Disease",
  "Myalgic Encephalomyelitis/Chronic Fatigue Syndrome",
  "Small Fiber Neuropathy",
  "Complex Regional Pain Syndrome",
  "Hypothyroidism",
  "Hashimoto’s Thyroiditis",
  "Addison’s Disease",
  "Myofascial Pain Syndrome",
  "Ehlers-Danlos Syndrome",
  "Osteoarthritis",
  "Lyme Disease",
  "Epstein-Barr Virus Infection",
  "Long COVID",
  "Postural Orthostatic Tachycardia Syndrome",
  "Irritable Bowel Syndrome",
  "Temporomandibular Joint Disorder",
  "Migraine",
  "Not sure"
];
